// Generates Swift enum tables from HearthstoneJSON's `enums.json`.
//
// Run by the HSEnumsPlugin build tool plugin on every build; the input is the
// committed, build-pinned copy in Data/HearthstoneJSON (refresh it with
// scripts/update-enums.sh). The output depends only on the input bytes, so the
// generation is reproducible.
//
// Usage: HSEnumsGenerator <gametag|enums> <enums.json> <enums.build> <output.swift>
//   gametag: the GameTag name tables for PowerParser
//   enums:   every other enum group, as `HS.<Group>` value types for HSData
//
// When one value has several names (Python enum aliases), the first name in the
// file is canonical, as in python-hearthstone. JSON object order is therefore
// significant, and this file reads it with its own order-preserving parser.

import Foundation

typealias Group = (name: String, members: [(name: String, value: Int)])

// MARK: - Order-preserving JSON reader for {"Group": {"NAME": int, ...}, ...}

struct EnumsJSONReader {
    enum Failure: Error, CustomStringConvertible {
        case unexpected(String, offset: Int)
        var description: String {
            switch self {
            case .unexpected(let what, let offset): "enums.json: expected \(what) at byte \(offset)"
            }
        }
    }

    private let bytes: [UInt8]
    private var index = 0

    init(_ data: Data) { bytes = Array(data) }

    mutating func read() throws -> [Group] {
        var groups: [Group] = []
        try objectEntries { reader, key in
            var members: [(name: String, value: Int)] = []
            try reader.objectEntries { reader, name in
                members.append((name: name, value: try reader.integer()))
            }
            groups.append((name: key, members: members))
        }
        skipWhitespace()
        guard index == bytes.count else { throw Failure.unexpected("end of input", offset: index) }
        return groups
    }

    private mutating func objectEntries(_ body: (inout EnumsJSONReader, String) throws -> Void) throws {
        try expect(UInt8(ascii: "{"))
        skipWhitespace()
        if peek() == UInt8(ascii: "}") { index += 1; return }
        while true {
            skipWhitespace()
            let key = try string()
            try expect(UInt8(ascii: ":"))
            skipWhitespace()
            try body(&self, key)
            skipWhitespace()
            if peek() == UInt8(ascii: ",") { index += 1; continue }
            try expect(UInt8(ascii: "}"))
            return
        }
    }

    private mutating func string() throws -> String {
        try expect(UInt8(ascii: "\""))
        var scalars: [UInt8] = []
        while let byte = peek(), byte != UInt8(ascii: "\"") {
            // Enum names are plain identifiers; escapes would mean the format changed.
            guard byte != UInt8(ascii: "\\") else { throw Failure.unexpected("an unescaped name", offset: index) }
            scalars.append(byte)
            index += 1
        }
        try expect(UInt8(ascii: "\""))
        return String(decoding: scalars, as: UTF8.self)
    }

    private mutating func integer() throws -> Int {
        let start = index
        if peek() == UInt8(ascii: "-") { index += 1 }
        while let byte = peek(), (UInt8(ascii: "0")...UInt8(ascii: "9")).contains(byte) { index += 1 }
        guard let value = Int(String(decoding: bytes[start..<index], as: UTF8.self)) else {
            throw Failure.unexpected("an integer", offset: start)
        }
        return value
    }

    private mutating func expect(_ byte: UInt8) throws {
        skipWhitespace()
        guard peek() == byte else { throw Failure.unexpected("'\(Character(UnicodeScalar(byte)))'", offset: index) }
        index += 1
    }

    private func peek() -> UInt8? { index < bytes.count ? bytes[index] : nil }

    private mutating func skipWhitespace() {
        while let byte = peek(), [0x20, 0x0A, 0x0D, 0x09].contains(byte) { index += 1 }
    }
}

// MARK: - Swift emission

/// The first name for each value, in file order.
func canonicalNames(_ members: [(name: String, value: Int)]) -> [(value: Int, name: String)] {
    var seen = Set<Int>()
    var result: [(Int, String)] = []
    for member in members where seen.insert(member.value).inserted {
        result.append((member.value, member.name))
    }
    return result.sorted { $0.0 < $1.0 }
}

func literal(_ s: String) -> String { "\"\(s)\"" }

func header(build: String) -> String {
    """
    // GENERATED by Tools/HSEnumsGenerator from Data/HearthstoneJSON/enums.json
    // (HearthstoneJSON, pinned to build \(build)). DO NOT EDIT.
    // Refresh the input with scripts/update-enums.sh; this file is rebuilt on every build.


    """
}

func emitGameTag(_ group: Group, build: String) -> String {
    var out = header(build: build)
    out += """
    extension GameTag {
        /// The HearthstoneJSON build the tag tables come from.
        public static let enumsBuild = \(build)

        /// Every tag name, aliases included, to its number.
        static let names: [String: Int] = [

    """
    for member in group.members.sorted(by: { $0.name < $1.name }) {
        out += "        \(literal(member.name)): \(member.value),\n"
    }
    out += """
        ]

        /// Each tag number's canonical name.
        static let nameByNumber: [Int: String] = [

    """
    for (value, name) in canonicalNames(group.members) {
        out += "        \(value): \(literal(name)),\n"
    }
    out += "    ]\n}\n"
    return out
}

let swiftKeywords: Set<String> = [
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func", "import", "init",
    "inout", "internal", "let", "open", "operator", "private", "precedencegroup", "protocol", "public",
    "rethrows", "static", "struct", "subscript", "typealias", "var", "break", "case", "catch", "continue",
    "default", "defer", "do", "else", "fallthrough", "for", "guard", "if", "in", "repeat", "return",
    "throw", "switch", "where", "while", "as", "false", "is", "nil", "self", "super", "throws", "true",
    "try", "Any", "Self", "Type", "Protocol", "some", "any",
]

/// Members the generated types declare themselves; enum names mapping to these get a trailing underscore.
let reservedMembers: Set<String> = ["rawValue", "name", "description", "hashValue", "canonicalNames", "valuesByName"]

/// `HERO_POWER` -> `heroPower`, `AttackVisualType` -> `attackVisualType`, `enUS` -> `enUS`.
func identifier(for name: String) -> String {
    var result: String
    if name.contains(where: \.isLowercase) {
        result = name.prefix(1).lowercased() + name.dropFirst()
    } else {
        let parts = name.split(separator: "_").map { $0.lowercased() }
        result = (parts.first ?? "") + parts.dropFirst().map { $0.prefix(1).uppercased() + $0.dropFirst() }.joined()
    }
    if result.isEmpty { result = "unnamed" }
    if result.first!.isNumber { result = "_" + result }
    if reservedMembers.contains(result) { result += "_" }
    return swiftKeywords.contains(result) ? "`\(result)`" : result
}

/// Groups whose name can't be a Swift type name.
let typeRenames = ["Type": "TagType"]  // `HS.Type` would clash with the metatype syntax.

func emitEnums(_ groups: [Group], build: String) -> String {
    var out = header(build: build)
    out += """
    extension HS {
        /// The HearthstoneJSON build these enums come from.
        public static let enumsBuild = \(build)
    }

    """
    for group in groups {
        let type = typeRenames[group.name] ?? group.name
        out += """

        extension HS {
            /// `\(group.name)` from HearthstoneJSON enums.json. Unknown numbers are kept as they are.
            public struct \(type): HSEnumeration {
                public let rawValue: Int
                public init(rawValue: Int) { self.rawValue = rawValue }


        """
        var used = Set<String>()
        for member in group.members {
            var id = identifier(for: member.name)
            if !used.insert(id).inserted {
                id = identifier(for: member.name + "_\(member.value < 0 ? "m\(-member.value)" : String(member.value))")
                used.insert(id)
            }
            out += "        public static let \(id) = \(type)(rawValue: \(member.value))  // \(member.name)\n"
        }
        out += "\n        public static let canonicalNames: [Int: String] = [\n"
        for (value, name) in canonicalNames(group.members) {
            out += "            \(value): \(literal(name)),\n"
        }
        out += "        ]\n\n        public static let valuesByName: [String: Int] = [\n"
        for member in group.members.sorted(by: { $0.name < $1.name }) {
            out += "            \(literal(member.name)): \(member.value),\n"
        }
        out += "        ]\n    }\n}\n"
    }
    return out
}

// MARK: - Main

let arguments = CommandLine.arguments
guard arguments.count == 5, ["gametag", "enums"].contains(arguments[1]) else {
    FileHandle.standardError.write(Data("usage: HSEnumsGenerator <gametag|enums> <enums.json> <enums.build> <output.swift>\n".utf8))
    exit(64)
}
do {
    let input = try Data(contentsOf: URL(filePath: arguments[2]))
    let build = try String(contentsOf: URL(filePath: arguments[3]), encoding: .utf8)
        .trimmingCharacters(in: .whitespacesAndNewlines)
    guard Int(build) != nil else { throw EnumsJSONReader.Failure.unexpected("a build number in \(arguments[3])", offset: 0) }
    var reader = EnumsJSONReader(input)
    let groups = try reader.read()
    let output: String
    if arguments[1] == "gametag" {
        guard let tags = groups.first(where: { $0.name == "GameTag" }) else {
            throw EnumsJSONReader.Failure.unexpected("a GameTag group", offset: 0)
        }
        output = emitGameTag(tags, build: build)
    } else {
        output = emitEnums(groups.filter { $0.name != "GameTag" }, build: build)
    }
    let outputURL = URL(filePath: arguments[4])
    // Leave an unchanged file alone so dependent modules aren't rebuilt.
    if (try? Data(contentsOf: outputURL)) != Data(output.utf8) {
        try Data(output.utf8).write(to: outputURL, options: .atomic)
    }
} catch {
    FileHandle.standardError.write(Data("HSEnumsGenerator: \(error)\n".utf8))
    exit(1)
}
